global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: datadog-webhook

receivers:
  - name: datadog-webhook
    webhook_configs:
      - url: 'https://api.${DD_SITE:-datadoghq.eu}/api/v1/integration/prometheus?api_key=${DD_API_KEY}'
        send_resolved: true
